### ISSUE TITLE
AndroidTV Support

### ISSUE THREAD

**Issue by Graphicscore** [proxer/ProxerAndroid#17]
Hi, this is more a feature request / nice to have.
I've used Proxer regularly now for a long time and would like to contribute back to the community.
Since animes can be enjoyed the most on big TV screens I would like to implement AndroidTV support for the Proxer android app. I know that a lot of people don't have an AndroidTV compatible device (yet) but seeing the development and engagement that the google development team is putting into the TV version I feel like they got a device coming up either with the next OS (P) or Q. No need to mention all the devices that are already running on ATV.

Since the android TV development isn't widely spead yet it will probably take a fair amount of time and tinkering to get it going properly. I'm not yet really familiar with RxJava and Kotlin which are used a lot in this project but I will try my best to match your coding style and the high quality of code that is maintained in this project.

I forked the repository and will develop on a side branch. If this feature is not wanted at all or already planned to be developed my somebody else please let me know.

Progess : 
====================================
# General
- [x] Add Leanback Dependencies to Project
- [x] Include Banner Icon for usage in TV Launcher
- [ ] Implement User Login and Session Handling
- [ ] Implement  [OnBoardDialog](https://developer.android.com/training/tv/playback/onboarding.html) - Maybe implement support for leanback in [Introduction](https://github.com/rubengees/introduction)
- [ ]  Captchas?

# TVActivity
- [x] Implement basic startup within a tv application using dynamic headers and a FragmentFactory

# AnimeBrowseFragment
- [x] Implement VerticalGridFragment for Browsing
- [x] Implement CardView with rating drawable
- [ ] Extend ImageCardView to support image loading via glide
- [ ] Implement Proxer Api usage with mapping for real data
- [ ] Link CardViews to an detailed Fragment ([AnimeDetailsFragment](https://d3prnml8t9ualt.cloudfront.net/fileadmin/_processed_/csm_MauTV_for_Android_TV_-_DetailsFragment_90a33c3fc8.png))
- [ ] Support for User WatchList
- [ ] Implement Search (this will be tricky ...)
- [ ] Implement support for [NowPlayingCard](https://developer.android.com/training/tv/playback/now-playing.html) 

# NewsFragment
- [ ] Implement a  custom Layout for large news

# AnimeDetailsFragment
- [ ]  Implement a layout for detailed information about anime
    - [ ] Thumbnail
    - [ ] Title
    - [ ] Description
    - [ ] Rating
    - [ ] Artists
    - [ ] Characters
    - [ ] Comments
    - [ ] References / Related Animes
    - [ ] Episodes
- [ ]  Link to an [VideoPlaybackFragment](https://developer.android.com/training/tv/playback/transport-controls.html)

# VideoPlaybackFragment
- [ ] Implement Support to play direct Proxer streams
- [ ] Implemenr Suppor to play supported streaming providers
- [ ] Implement linking to crunchyroll app etc

**Comment by rubengees** [comment]
That sounds great! I also thought about that, but never actually did it, because I have no AndroidTV device and testing on my phone doesn't seem right.
I am still not sure if an AndroidTV app should be an app on it's own or not, maybe you can share your findings once you have started!

**Comment by Graphicscore** [comment]
I'm slowly starting to get a hold of the Leanback framework. It's currently running on Java but I'll migrate it Kotlin soon.
![Launch Menu](https://i.imgur.com/fUdvq6y.png)
![InApp](https://i.imgur.com/DJBYiyV.png)

**Comment by rubengees** [comment]
Cool! Starting with Java and converting these files to Kotlin has helped me too. 

The Kotlin plugin also has an option to convert [Java to Kotlin](https://www.jetbrains.com/help/idea/converting-a-java-file-to-kotlin-file.html) which you can compare to see what is happening. The [Decompile Kotlin to Java](https://stackoverflow.com/questions/34957430/how-to-convert-a-kotlin-source-file-to-a-java-source-file?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) option is also helpful to see what is generated under the hood.

Once you have Kotlin code remember to run the `detektCheck` and `ktlintCheck` tasks on it to find potential problems and code style issues.

**Comment by Graphicscore** [comment]
Awesome! Will do!
Github won't let me create issues/tickets inside my fork sadly so I've added a rough sketch of my ToDo-List on the first post in this discussion. I didn't wanted to spam todos in the issue board of the proxer app...., there are probably far more points than I've noted here yet - hah.

**Comment by Graphicscore** [comment]
I'm running into the 65k DEX limitation even though multidexing is already turned on ....
Do you have any ideas ? I've just added code , no external libraries
```
Information:Gradle tasks [:assembleDebug]
Warning:The option 'android.enableD8' is deprecated and should not be used anymore.
Warning:The rule `-keep public class *extends java.lang.annotation.Annotation {
Error:java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Error:com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Error:com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Error:The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
Error:com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
Error:	at com.android.dx.merge.DexMerger$8.updateIndex(DexMerger.java:564)
Error:	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:275)
Error:	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:573)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:165)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:197)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Information:BUILD FAILED in 1m 19s
Information:17 errors
Information:2 warnings
Information:See complete output in console
```

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 19s
```

**Comment by rubengees** [comment]
Since there has been no activity on this for quite some time, I'm closing this issues for now.
If you ever come back to it, please reopen!

**Comment by Graphicscore** [comment]
It took a year 😄 . I finally moved my TV from the living room into my bedroom so this topic just came to mind again. Maybe this time I will stick around and push this through because now I actually have a proper TV to use it on. Sadly they made the leanback tv framework even more complex and weird compared to a year ago. I'm probably better off just starting from scratch again. 

I will report if I make any noticable progress.

PS: Since last year they published x64 tv system images for the emulator which work quite well. 🎉

**Comment by rubengees** [comment]
Cool, looking forward! Let me know if I can help you with anything :)

**Comment by Graphicscore** [comment]
Is it normal that the repository requires the latest preview build ? 

> This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.

**Comment by rubengees** [comment]
Yes, I also use this project to explore the latest features and technologies in the Android world, so Android Studio and most libraries are preview versions.

**Comment by xdreamskillzxx** [comment]
@Graphicscore someone already implemented this. But as it is it is already outdated. But maybe you can use some of this code. Look here for more [Info](https://github.com/inv3rse/ProxerTv)
