### ISSUE TITLE
App Crashes when loading stream from proxer.me

### ISSUE THREAD

**Issue by glassp** [proxer/ProxerAndroid#40]
Android version: 11
Build version: 1.11.1 
Current date: 2020-12-22 18:45:48 
Device: Google Pixel 4 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.content.res.Resources$NotFoundException: Drawable me.proxer.app:drawable/mr_button_dark with resource ID #0x7f080222
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/mr_button_dark.xml from drawable resource ID #0x7f080222
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:891)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
	at android.content.res.Resources.loadDrawable(Resources.java:993)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
	at android.content.res.Resources.getDrawable(Resources.java:922)
	at android.content.res.Resources.getDrawable(Resources.java:897)
	at e6.v.c.b.doInBackground(:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.view.InflateException: Class is not a Drawable x
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:218)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:141)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
	at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:954)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:877)
	... 11 more
Caused by: java.lang.ClassCastException: class x cannot be cast to android.graphics.drawable.Drawable
	at java.lang.Class.asSubclass(Class.java:2482)
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:205)
	... 16 more

**Comment by rubengees** [comment]
Thanks! This is known and fixed in 516b6847f9dd2c65620d80fda919c2fdebd31ead.
