### ISSUE TITLE
App doesn't open for me

### ISSUE THREAD

**Issue by OwO-tism** [proxer/ProxerAndroid#47]
When trying to open the app it immediately crashes. This happens both with the Play Store version (wich has been removed) and the GitHub download.

Using a Xiaomi Mi Note 10, not sure why this happens but here is the crash report:

----------------------------------------------------------------------------------------
java.lang.RuntimeException: Unable to create application me.proxer.app.MainApplication: v6.d.c.f.d: Could not create instance for [Single:'r6.a.a.j2.y.g']
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6609)
	at android.app.ActivityThread.access$1400(ActivityThread.java:227)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1890)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7584)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: v6.d.c.f.d: Could not create instance for [Single:'r6.a.a.j2.y.g']
	at v6.d.c.g.c.a(:29)
	at v6.d.c.g.d.a(:2)
	at v6.d.c.g.d.b(:3)
	at v6.d.c.m.b.b(:6)
	at v6.d.c.m.b.a(:20)
	at v4.b(:69)
	at n6.k.getValue(:5)
	at me.proxer.app.MainApplication.a(Unknown Source:2)
	at me.proxer.app.MainApplication.onCreate(MainApplication.kt:129)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6604)
	... 8 more
Caused by: i6.i.c.a.c0.a.p0: Protocol message contained an invalid tag (zero).
	at i6.i.c.a.c0.a.i0.o(:15)
	at i6.i.c.a.b0.h2.z(:1)
	at i6.i.c.a.y.a.b.b(:5)
	at i6.i.c.a.y.a.b.a(:3)
	at g6.c0.a.d.a(:12)
	at r6.a.a.j2.y.c.d(:7)
	at r6.a.a.j2.y.c.a(:18)
	at r6.a.a.j2.y.g.<init>(:2)
	at r6.a.a.a0.g(:8)
	at v6.d.c.g.c.a(:14)
	... 18 more

**Comment by rubengees** [comment]
This looks like a known crash produced by restoring corrupted backups. Can you try to delete the app data in the system settings?
